GET http://localhost:3000/api/contacts

###
GET http://localhost:3000/api/contacts/63f5cde4f479a85b21c31d34

###
GET http://localhost:3000/api/contacts/favorite

### add contact
POST http://localhost:3000/api/contacts
Content-Type: application/json

{
    "name": "nguyen huu dat dep trai",
    "favorite": true
}


### update contact
PUT http://localhost:3000/api/contacts/63f5da94eb44ecf7f19af5a3
Content-Type: application/json

{
    "favorite": false
}


###
DELETE  http://localhost:3000/api/contacts/63f59c48efaac664ff3c16ca

### destroy
DELETE  http://localhost:3000/api/contacts

###
GET http://localhost:3000/auwdhfsiefijsef/sefsefsef/sefse

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "datnh",
    "password": 123123
}

###
GET http://localhost:3000/login