GET http://localhost:3000/api/contacts

###
GET http://localhost:3000/api/contacts/63f5cde4f479a85b21c31d34

###
GET http://localhost:3000/api/contacts/favorite

### add contact
POST http://localhost:3000/api/contacts?key=dat


### update contact
PUT http://localhost:3000/api/contacts/6422db66382fc92285be3012
Content-Type: application/json

{
    "name": "nguyen huu dat update 2"
}


###
DELETE  http://localhost:3000/api/contacts/63f59c48efaac664ff3c16ca

### destroy
DELETE  http://localhost:3000/api/contacts

###
GET http://localhost:3000/auwdhfsiefijsef/sefsefsef/sefse

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "datnh",
    "password": 123123
}

###
GET http://localhost:3000/login